output_dir: "./results"
logging_dir: ./logs"
logging_steps: 10
save_steps: 512
save_total_limit: 3
num_train_epochs: 20
per_device_train_batch_size: 16
per_device_eval_batch_size: 16
gradient_accumulation_steps: 2
learning_rate: 0.008
weight_decay: 0.05
eval_strategy: "steps"
eval_steps: 256
load_best_model_at_end: True
dataloader_pin_memory: True
dataloader_num_workers: 2
seed: 42
report_to: "wandb"
remove_unused_columns: False